### ISSUE TITLE
Add comparison_single_stat item type

### ISSUE THREAD

**Issue by aalpern** [urbanairship/tessera#126]
Just like the comparison summation table (issue #125), add a variant of the ``singlestat` presentation type that compares a single summation value between two queries. Again - queries can both be explicitly selected, or one can be derived from the first plus a time range modifier. 

Also timeshift variant (like `timeshift_summation_table`)

**Comment by clohtd** [comment]
I would find this to be very useful.  I'm using two single stats to show memory utilization vs total memory.  To have that all fit in to one cell would be very nice.

**Comment by aalpern** [comment]
Complete on the development branch.
