### ISSUE TITLE
Add bar chart dashboard item

### ISSUE THREAD

**Issue by aalpern** [urbanairship/tessera#160]

**Comment by aalpern** [comment]
![image](https://cloud.githubusercontent.com/assets/784846/6521167/7af72dc4-c388-11e4-9d7f-f12e0b446055.png)

![image](https://cloud.githubusercontent.com/assets/784846/6521171/8fc02404-c388-11e4-81bb-fd1065c61a08.png)

**Comment by clohtd** [comment]
Yes!  Nice!

**Comment by aalpern** [comment]
https://github.com/jasonroman/flot-barnumbers-enhanced looks good for enhancing `discrete_bar_chart`
