### ISSUE TITLE
Document need for Access-Control-Allow-Origin in graphite web config

### ISSUE THREAD

**Issue by dchang0** [urbanairship/tessera#327]
I've tried both the git clone (v 0.4.6) and pip install tessera (v 0.4.5) methods of installing tessera, and everything seems to work except for the queries.

Even the default queries, absolute(randomWalkFunction("query0")), fail.

When using the git clone method, I checked that versions of requisites matched the versions specified in the requirements.txt and dev-requirements.txt files. I also tried upgrading each requisite package to the latest, and that made no difference.

See screenshot for the error as it looks.

![tesseraerror](https://cloud.githubusercontent.com/assets/8884074/4639222/ba15b3da-5408-11e4-8d35-24cc8a13e42a.gif)

**Comment by aalpern** [comment]
Updated documentation
