### ISSUE TITLE
Pie Chart Shows "Undefined" for Interactive Chart Render

### ISSUE THREAD

**Issue by SM2000** [urbanairship/tessera#352]
After selecting "Interactive" chart style, pie charts show "Undefined" as the key (on hover) whereas on Static chart style, the key is correct.

![image](https://cloud.githubusercontent.com/assets/2138280/5565286/0ab34106-8f44-11e4-81a7-e7848d27dcdf.png)

**Comment by mattnthat** [comment]
Agree. Big blocker to usage. Not using any Interactive charts to avoid this doesnt give a great outcome.

**Comment by aalpern** [comment]
Thanks for the fix!
