### ISSUE TITLE
Consider downsampling long time periods

### ISSUE THREAD

**Issue by aalpern** [urbanairship/tessera#365]
Rendering of flot charts gets slower with long time spans (weeks), and the large number of data points it's often more than can actually be rendered onscreen. Consider using [flot-downsample](https://github.com/sveinn-steinarsson/flot-downsample/) to reduce the number of points actually plotted and improve performance.

**Comment by aalpern** [comment]
Incorporated with an adaptive threshold.

**Comment by aalpern** [comment]
Example - all data:

![screen shot 2015-03-09 at 7 22 10 pm](https://cloud.githubusercontent.com/assets/784846/6586210/161daeb8-c735-11e4-9ddf-ef1f9a6655e2.png)

Downsampled:
![screen shot 2015-03-09 at 7 21 42 pm](https://cloud.githubusercontent.com/assets/784846/6586212/1ad985c6-c735-11e4-8aa2-fba5605179c3.png)

**Comment by clohtd** [comment]
Beautiful.  This will be very helpful.
