### ISSUE TITLE
Use flot's pie chart in flot renderer

### ISSUE THREAD

**Issue by aalpern** [urbanairship/tessera#371]
The flot renderer currently uses nvd3 for rendering pie/donut charts. Flot is perfectly capable of rendering pie & donut charts on its own though - update the flot renderer to actually use flot for this chart type. Then we could avoid loading `nvd3` when we don't need it. 

(This also goes towards my desire to remove the nvd3 renderer from the standard build, and move it to the unsupported extensions directory).

**Comment by clohtd** [comment]
Yes!  Perhaps satisfy this by figuring out how to support flot's plugins.  Their automarkings plugin is also on my radar.  Agreed that nvd3 can be moved to unsupported extensions.  It's so slow that I can't even use it.

**Comment by aalpern** [comment]
![image](https://cloud.githubusercontent.com/assets/784846/6521195/093e4e6e-c389-11e4-9587-289f2230f283.png)
