### ISSUE TITLE
error: [Errno 32] Broken pipe | Call a plumber

### ISSUE THREAD

**Issue by clohtd** [urbanairship/tessera#372]
Oops, I broke a pipe.  I've just started using Tessera and am serving it with Python.  It's becoming very slow.  I'm thinking I need to move it to Apache+wsgi.

Anyways, if you care about this, here you go.  I'm starting to throw a bunch of these and am about to start investigation.  I'll update this once I learn more.

----------------------------------------
Exception happened during processing of request from ('192.168.1.20', 61159)
Traceback (most recent call last):
  File "/usr/lib64/python2.6/SocketServer.py", line 283, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib64/python2.6/SocketServer.py", line 309, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib64/python2.6/SocketServer.py", line 322, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python2.6/SocketServer.py", line 618, in __init__
    self.finish()
  File "/usr/lib64/python2.6/SocketServer.py", line 661, in finish
    self.wfile.flush()
  File "/usr/lib64/python2.6/socket.py", line 297, in flush
    self._sock.sendall(buffer(data, write_offset, buffer_size))
error: [Errno 32] Broken pipe
----------------------------------------

**Comment by clohtd** [comment]
It seems to be related to the slow performance of the hosting virtual machine.  Able to recreate by hitting save on a chart and then immediately clicking on Dashboards.  Seems to occur when the chart save is in progress.  If this is true, then perhaps the chart save needs to be backgrounded.

**Comment by clohtd** [comment]
Oops, I didn't intend to close it.

**Comment by aalpern** [comment]
This sounds like it's an issue with your setup being underpowered (although..the backend isn't exactly doing anything intensive; it's mostly just I/O, and not that much of it). 

Saves will not be made async - the UI needs to know if the save succeeded or not. If that's dumped in a queue and done asynchronously from the API call, you won't know if your save failed.

**Comment by clohtd** [comment]
Thanks for the response.  It does feel as though it is related to system performance.  Oddly, Tessera is isolated on it's own VM, and the VM is very well fed.  Python is running at 9% cpu.  A dashboard save commits only a very small amount to disk.  This sure seems to be a lightweight application.  Yet sometimes saves are immediate, and sometimes they take up to 4 or 5 seconds.  I'm beginning to wonder if it's a client-side problem that is manifesting in the backend as this error; browser rendering or something.  I'm also suspicious of this specific dashboard.  It has begun dropping out rendering of some of the standard_time_series graphs.  I have 10 standard_time_series graphs and 10 singlestats on a dashboard rendering at 1 hour (representing 2 servers).  Occasionally during a refresh, the time series won't render if interactive mode is enabled.

I'll keep poking and let you know what I find.  Hopefully this will help someone else.

**Comment by aalpern** [comment]
Have you used the Webkit console to find out what's happening with the HTTP requests? That will tell you a lot about whether you're seeing something like dropped connections on the client side.

**Comment by clohtd** [comment]
OK, the underlying problem was unrelated to Tessera, although Tessera was impacted by it.  My carbon collector had become severely overloaded.  The graphite renderer was timing out.  I used the Webkit console per your suggestion and was then able to see the timeouts; thanks!  So this is closed and I hope will help someone in the future.  Thanks Adam.

(Side note:  Maybe in the future it would make sense to try to catch this and tell the end user that someone is slow with graphite.  Once I implemented Tessera I stopped using graphite-web as frequently so I didn't notice the lag.  Since Tessera is now the front-end, maybe it would be nice to have it say "hey go fix your graphite-web."  I don't know if actually would be nice, just thinking...)

**Comment by aalpern** [comment]
@clohtd Thanks for the writeup! I've already started with #370 - instrumenting query loading times so tessera can mark expensive/slow dashboards.

There already is an error handler on loading queries that should display an error notification in the upper right corner when a query fails to load (see [here](https://github.com/urbanairship/tessera/blob/master/js/models/data/Query.js#L196)). Perhaps there are some browsers scenarios where that doesn't work.
