### ISSUE TITLE
Setting time period broken in Isolate transform

### ISSUE THREAD

**Issue by aalpern** [urbanairship/tessera#386]

**Comment by PrFalken** [comment]
It works when you set the time period and then reload the page. But this is very annoying indeed.
Thanks for your massive work improving tessera these days !

**Comment by aalpern** [comment]
Yeah, I've internalized the workaround so I immediately hit command-R after selecting the time range :smile: But obviously, it'd be better if it worked again.

**Comment by aalpern** [comment]
I've been investigating this morning - I initially assumed this was a data loading problem, but it turns out it's some kind of redraw problem in  the `flot` and 'nvd3' renderers. The query is being reloaded properly with the changed range, and the summation table updates correctly. So does the chart if using the `graphite` renderer.

**Comment by aalpern** [comment]
D'oh! Just a stupid query data caching bug. Fixed.
