### ISSUE TITLE
Problem with standard time series charts not connecting lines

### ISSUE THREAD

**Issue by clohtd** [urbanairship/tessera#401]
Problem with Tessera standard time series using sloped-line rendering instead of connected-line.

I have some charts which need to be rendered in graphite as connected line in order to look like a chart.  Tessera's standard time series chart seems to only render as sloped line, which leaves my data as points instead of as connected lines.

I believe this is happening because I have 1s samples in carbon and some of my data is only occurring once ever 5 seconds.  So I don't have enough data for sloped line to connect the dots.

Is there a way for me to change the standard time series chart to use the connected line rendering method found in graphite-web?

**Comment by aalpern** [comment]
This came up once before - #326. Looks like there would be no harm in setting `lineMode=connected` as the default. 

With the upcoming 0.6 release, `flot` will be the default renderer (and you'll really want to use it, or else you'll miss out on all the new chart types).

**Comment by clohtd** [comment]
Shoot...I tried to find a previous issue before posting.  Sorry for the dup.

I probably misunderstand something?  I thought my only options were flot or nvd3, so I assumed static charts were using flot.  Can I switch to flot without using interactive?  Interactive/flot doesn't work for me at all.  The charts don't render and the mouseover data is all zeros.  I'm realizing now that I should look for a bug report for interactive/flot not functioning and perhaps report that.  Interactive/flot doesn't work at all in Chrome 40.0.2214.115.  In Firefox 36.0.1, almost none of the charts render in interactive/flot except for one, and that one doesn't draw sloped lines but instead draws vertical lines (undesirable, slopes help to visualize trends.)

If switching to flot is a solution to this, is interactive my only option with flot?  No static?  Is interactive/flot the same as "using flot?"  If so, then the next release will break all of my charts, rendering everything blank, so I should figure out how to help report a fixable bug for that.

**Comment by aalpern** [comment]
Static charts are rendered by graphite-web, not flot, and will remain an option. 

For interactive charts, there used to be two options (flot, which uses Canvas, and nvd3, which uses SVG). As of now, on the `development` branch, I've removed the nvd3 option, since flot performs much better overall. 

If you're having issues with flot charts, please run tessera from the development branch and see how that works for you first - there have been a lot of bug fixes and improvements.
