### ISSUE TITLE
tags links break when using sublocation within nginx

### ISSUE THREAD

**Issue by clohtd** [urbanairship/tessera#403]
latest development head + nginx + supervisor

URL = http://servername:8000/tessera/

When I click on tags, the "/tessera" part of the path is ignored and it attempts to load http://servername:8000/dashboards/tags/test

If I manually edit the path to http://servername:8000/tessera/dashboards/tags/test then it loads properly.

There's something about the hyperlinks for tags that isn't including the full root url.

**Comment by clohtd** [comment]
/api also isn't running beneath the /tessera

going to workaround it by removing the /tessera

**Comment by aalpern** [comment]
That sounds like a problem with your nginx config.

**Comment by aalpern** [comment]
FYI, you might want to check your config against this Docker image I set up to test running Tessera on a sub-path - https://github.com/aalpern/docker-tessera-test-nginx

I haven't tested that on the development branch yet; will do that when it's closer to release.

**Comment by clohtd** [comment]
That docker image is what I followed.  I never could prove that it was the configuration.
