### ISSUE TITLE
Implement a connected line mode for flot

### ISSUE THREAD

**Issue by clohtd** [urbanairship/tessera#404]
I upgraded to the latest development head today to see if flot would render my charts.  I found that flot does not render, while "graphite" rendering looks great.
graphite
![graphite](https://cloud.githubusercontent.com/assets/11097766/6628446/cc3ee804-c8c2-11e4-8a10-43418ece3415.png)
flot
![flot](https://cloud.githubusercontent.com/assets/11097766/6628448/ce4c97fe-c8c2-11e4-99ae-0cd6b89520b6.png)

Browser = Chrome Version 41.0.2272.89 m on Windows 7 x64

**Comment by clohtd** [comment]
Tessera page indicated "SM Tessera v0.6.0.dev"

**Comment by clohtd** [comment]
The demo time series chart works with flot.  It's only charts using my own data.

**Comment by clohtd** [comment]
It seems to be the same problem as https://github.com/urbanairship/tessera/issues/401 with lines not connecting between the series.  Stacked area mode DOES render the data.  Barcharts also render the data.  It's just the standard time series which seems to be using a sloped-line type of renderer.

**Comment by aalpern** [comment]
It clearly is rendering your data - you just have extremely sparse data. How does it look if you render time series that have more frequent time datapoints?  For example, just try one of the auto-generated random data queries - `absolute(randomWalkFunction("query11"))`

**Comment by aalpern** [comment]
Flot doesn't seem to have any equivalent option to render connected lines in the absence of data points. Perhaps there's a plugin out there to do it.

**Comment by clohtd** [comment]
Maybe this one:  https://github.com/MichaelZinsmaier/CurvedLines

**Comment by clohtd** [comment]
It is definitely an issue with sparse data.  I setup a sample data generator at high rates and that looks fine.
