### ISSUE TITLE
Why do summation tables occasionally do this? "1.800000000000001e+284Y"

### ISSUE THREAD

**Issue by clohtd** [urbanairship/tessera#408]
net.eth5.txkB_s	0.00	1.800000000000001e+284Y	5e-324	0.00	0.00	0.00

Any ideas on why summation tables occasional do the above to my data?  Sometimes it gives me a 0, and sometimes it says "1.800000000000001e+284Y"

**Comment by clohtd** [comment]
...and this 1.7976931348623157e+308.  At least that number can be found in a google search.  I "think" it's telling me that the metric is out of bounds.

**Comment by aalpern** [comment]
It's just a bug in calculating the min and max in Summation.js. Fixed on the `development` branch a few days ago.
