### ISSUE TITLE
tessera calls JSON *and* PNG formats if interactive=false

### ISSUE THREAD

**Issue by PrFalken** [urbanairship/tessera#410]
Working with 0.4.3 on production, I found that tessera calls the Graphite API twice event if it uses only the PNG mode. 
- if paramater interactive=false in the URL --> calls graphite with format=json and again with format=png
- if parameter interactive=true in the URL --> call graphite with format=json only.
- it looks like each item in the dashboard is set with a property interactive=true
- setting them to false in the DB or removing the property doesn't solve the issue.

Even weirder : this does not happen on all the dashboards ! I don't understand how buggy dashboards are related. This obviously dramatically degrade the user experience when querying a big timeframe (unusable over 1 week :( )

Any hint would be much appreciated !

**Comment by aalpern** [comment]
If you have any text presentations, the query for them will be loaded as JSON. So, if you have a graph and a singlestat that share a query, it will always be loaded as JSON (obviously - we can't extract numbers from a PNG), regardless of the `interactive` parameter -- that only affects graphs. 

The only dashboard that will never load JSON data is one that's 100% graphs in non-interactive mode. 

It's certainly possible there's a bug in there too, of course. It's been slightly re-worked in the dev branch, and it's on my list for further refactoring & cleanup.

**Comment by PrFalken** [comment]
There is definitely a bug : even if I have only one table and many graphs, there are two http calls for each graph : one with format=json and the other with format=png. for my dashboard that's 27 json calls and 26 png calls for 26 graph items and 1 table item.
when I remove the only table item from my dashboard, there is no json call anymore and the dasboard loads fast again, even with a timeframe of 1 year.

I tested this with a few versions of tessera and it looks like it has always been there.

**Comment by aalpern** [comment]
Thanks - I'm pretty sure I see what's going on . Bad plumbing :)

**Comment by clohtd** [comment]
Nice find PrFalken.

**Comment by aalpern** [comment]
OK, pull request #415 fixes it - I'm going to test it some more on our more complicated dashboards before merging it, but so far it looks much improved.

**Comment by aalpern** [comment]
Merged into `development`

**Comment by aalpern** [comment]
@PrFalken This is fixed on the `development` branch now. I'm going to wrap up the 0.6 release this week, which will include this fix.

**Comment by PrFalken** [comment]
that's great ! thank you.
