### ISSUE TITLE
Charts does not render on a docker aalpern/tessera-simple deployment

### ISSUE THREAD

**Issue by tzach** [urbanairship/tessera#413]
Probably my own fault and not a real bug...
I have a Graphite server running on EC2:
```
sudo docker run --net=host lopter/collectd-graphite
```
I try to add a tessera container on the same server with 
```
sudo docker run -P --net=host -e GRAPHITE_URL=http://ip -it aalpern/tessera-simple
```
[For ip I already try EC2 private and public IP, localhost]

I get the dashboard UI working, but there are not charts.
On the browser console I get:
```
GET http://localhost/render?format=json&from=-1h&tz=Etc%2FUTC&target=group%28ab…2%29%29%29&jsonp=jQuery111204286330200266093_1427034471905&_=1427034471906 net::ERR_CONNECTION_REFUSED
```
What am I'm doing wrong?
Why do the browser look for local host?

Thanks

**Comment by aalpern** [comment]
Please file issues with the docker image on the github repo for that image - https://github.com/aalpern/docker-tessera-simple. 

Thanks!

**Comment by tzach** [comment]
Thanks, just did.

**Comment by aalpern** [comment]
thanks!
