### ISSUE TITLE
Allow time span formats in the various `format` fields

### ISSUE THREAD

**Issue by aalpern** [urbanairship/tessera#414]
Numeric values are formatted by `d3.format`. It would be nice to support formatting human readable time span formats as well, for example when you want to display a mean or max latency value in a singestat, particularly for time periods longer than millis or seconds (for example, metrics for long-running batch tasks, where a task by run to hours). 

See, for example, http://momentjs.com/docs/#/durations/

Or https://github.com/codebox/moment-precise-range

**Comment by mkavanagh** [comment]
I've implemented this for my own purposes as a new item type using humanize-duration; it looks like this:

![image](https://cloud.githubusercontent.com/assets/2299086/7410589/29c771f4-ef28-11e4-8925-5400cd2e325b.png)

The branch is https://github.com/mkavanagh/tessera/tree/timerstat - there's a non-minified library and the  conventions (e.g. naming) I've used are a bit different to the rest of the codebase, but those things can change so if you're interested in a PR let me know.

**Comment by barthoda** [comment]
@mkavanagh yes please

**Comment by aalpern** [comment]
Nice! Please do submit a PR - I've got a dashboard that I'll be happy to start using this on right away. 

The conventions are changing as I'm gradually moving the codebase to TypeScript anyway :)

**Comment by aalpern** [comment]
@mkavanagh FYI, I took your code and translated it to the new TypeScript dashboard item model - I'll have it up in a PR shortly. Thanks very much for putting this together! It only took me a couple of minutes to translate it to the new cleaned up model.

**Comment by aalpern** [comment]
Merged into the `development` branch.
