### ISSUE TITLE
Isolate transform doesn't use interactive charts anymore when main renderer is Graphite

### ISSUE THREAD

**Issue by PrFalken** [urbanairship/tessera#418]
I may have missed something, but is it possible to set the png mode by default on the latest version ?
Setting INTERACTIVE_CHARTS_DEFAULT to False doesn't change anything.

**Comment by aalpern** [comment]
Yes, set `CHART_RENDERER = 'graphite'` in `config.py`

**Comment by PrFalken** [comment]
Allright it works. But now when I hit "Isolate", I have the png version.
Initially you could have PNGs on the dashboard and Flot on the "isolate" page.

Is it still possible ?

**Comment by aalpern** [comment]
Ah, that looks like an "oops".

**Comment by PrFalken** [comment]
Although it's good to have PNGs in the isolate view but I'd like to have it configurable.

**Comment by PrFalken** [comment]
Hello, is there anything we can do with that one ?

**Comment by aalpern** [comment]
Yes - with the refactoring almost done on the `development` branch, I'll be addressing this shortly. All charts are going to get the ability to override the default renderer, so the transform can specify the renderer to use.

**Comment by aalpern** [comment]
Fixed.

**Comment by PrFalken** [comment]
Thank you so much !
