### ISSUE TITLE
Export dashboard to pdf:  jsPDF

### ISSUE THREAD

**Issue by clohtd** [urbanairship/tessera#424]
Would be nice to have something like this, to allow us to export an entire dashboard to a pdf.
https://github.com/MrRio/jsPDF

**Comment by aalpern** [comment]
jsPDF looks like it's a very simple API for creating PDFs from scratch. What you need is something that renders HTML to PDF with good fidelity. The only approach I've ever seen that works for that is using WebKit - I've succesfully used `wkhtmltopdf` in the past -- see http://wkhtmltopdf.org/

However, given that's an external program, integrating it isn't very simple - I generally view this as something that's a general problem outside the scope of Tessera.
