### ISSUE TITLE
Export Dashboard

### ISSUE THREAD

**Issue by tzach** [urbanairship/tessera#425]
It would be useful to export a dashboard in a format which can later be uploaded to a new instance of Tessra.
Any way to do it right now?

**Comment by clohtd** [comment]
I do this today using curl on linux.

* curl --get -d "definition=true" http://servername:5000/api/dashboard/25 > template.json
* curl -X POST --header "Content-Type: application/json" -d @template.json http://servername:5000/api/dashboard/

I just used that to export all of my dashboards from an old server and upload them to a new server.
I also use this to rapidly create new dashboards using a template.  I download the template, find/replace strings, then upload as a new dashboard.

**Comment by tzach** [comment]
Cool.
This is what I was looking for.
