### ISSUE TITLE
user input for dashboards

### ISSUE THREAD

**Issue by filippog** [urbanairship/tessera#427]
hi,
thanks for tessera, looks really useful!
I think it'd be nice to support having user input passed to the dashboard templates so variables can be expanded, this comes handy for example to have a generic "host dashboard" where the query has e.g. `{{host or "localhost"}}` and will expand it to whatever value is provided by the user on `/api/dashboard`.
Not sure how to best implement this client-side, perhaps when asking the definition tessera would also return what variables are expected. What do you think?

thanks!

**Comment by clohtd** [comment]
Duplicate of this:  https://github.com/urbanairship/tessera/issues/426

Please see this statement on the front page:  "Tessera is initially focused on information presentation - it does not NOT address the areas of metric discovery or query composition (although it may in the future)."

The graphs in Tessera are more visually appealing than anything else I have found.  Grafana has query composition but it's cumbersome to use; graphite is faster.  Graph explorer tries to improve on it and hasn't so far.  Of everything I have looked at, so far, graphite still has the easiest composition component; which isn't to say that it's good, merely the best which I have found.

**Comment by filippog** [comment]
thanks for the quick reply!
I see what you mean, basically what I need is more along the lines of https://github.com/PrFalken/tessera-generate, I'll try poking at that too, thanks!

**Comment by aalpern** [comment]
@filippog Every query in tessera gets expanded by the Handlebarsjs template engine. There's not much documentation on tessera-specific extensions to it yet (there are a few), but you can easily do basic variable substitution in your queries. Every URL parameter is passed as part of the template context, so you can have `{{host}}.mymetrics.thing.count` in a query, and it will be replaced with whatever you pass for the variable `host` in the URL query string when loading the dashboard.

**Comment by filippog** [comment]
@aalpern sweet, thanks! I think that might do just fine for my host-dashboard use case and perhaps others
