### ISSUE TITLE
Query with multiple targets could not be edited

### ISSUE THREAD

**Issue by michael-bouvy** [urbanairship/tessera#433]
I've successfuly created several queries in my Tessera dashboard from Graphite URLs, each including multiple targets.

But, when editing those queries, the values in the targets array are "joinded" with a comma, and saved like that as a string, instead of an array. As a result, only the first target is used to render the graph.

A possible workaround I've tried to implement is using the newline character `\n` as targets separator, and spliting targets values upon this separator when saving them.

However, when displaying/editing the queries, the targets values are once again joined with a comma, and I couldn't tell where it's done.

**Comment by aalpern** [comment]
Yup - the editor unfortunately doesn't support queries with multiple targets as of this time. It's already on the enhancements wish list (see #297). The workaround is to put a `group(...)` around your targets.

**Comment by michael-bouvy** [comment]
Thanks for your quick answer and sorry for the duplicate.

Congrats for the great job ! :+1:

**Comment by aalpern** [comment]
No worries :)
