### ISSUE TITLE
Recommended method of installation

### ISSUE THREAD

**Issue by BackSlasher** [urbanairship/tessera#434]
Aside from docker, what method is recommended for new installations?
I saw on [your site](http://urbanairship.github.io/tessera/docs/) that you recommend cloning this repo, but on [this repo](https://github.com/urbanairship/tessera#from-source), you recommend installing via pip.
Is there a difference?

**Comment by aalpern** [comment]
@BackSlasher Using `pip` will get you the latest tested, labeled release. This usually corresponds to the current state of the `master` branch, but not always. 

Obviously, if you want to hack on the source, you need to clone the github repository.
