### ISSUE TITLE
how to change line name?

### ISSUE THREAD

**Issue by juwlee** [urbanairship/tessera#439]
I have a few charts imported from graphite. Some of the lines on the charts are sum of other time series, so their names are quite long. Is there a way to shorten them? I looked around for line name assignment but without much luck. Could you give me a pointer?

**Comment by aalpern** [comment]
Yes, use one of the variety of alias functions in your Graphite query. http://graphite.readthedocs.org/en/latest/functions.html#graphite.render.functions.alias
