### ISSUE TITLE
Dashboard-level renderer selection

### ISSUE THREAD

**Issue by bitprophet** [urbanairship/tessera#460]
This follows from the recently added per-graph-item renderer option - if one has a sufficient number of "works best in PNG" graphs, having to update all of them individually is quite time consuming.

Hopefully simple-ish to add another field/attr to the dashboard level which serves as a default for the per-graph field.

**Comment by aalpern** [comment]
Here's the function that picks the renderer to use - checking the dashboard item and falling back to the global default. 

https://github.com/urbanairship/tessera/blob/development/src/ts/charts/core.ts#L79

after checking the dashboard item, it can check `item.dashboard.renderer` before the global default. Easy peasy.

**Comment by aalpern** [comment]
Actually, putting the override on `DashboardDefinition`, not `Dashboard`, is probably the way to go, for multiple reasons:

* Adding a new field to `Dashboard` would require a new column in the database, and a schema migration
* `DashboardDefinition` will be the eventual unit of dashboard re-use (see issue #135), and this setting should be included in the re-used definition.

**Comment by aalpern** [comment]
Done
