### ISSUE TITLE
Autorefresh stopped working on 0.7

### ISSUE THREAD

**Issue by jve** [urbanairship/tessera#468]
Hi,

We just upgraded to tessera 0.7 and found that the autorefresh stopped working.
We are using firefox 38.

I had a quick peak in the code but I am in no way a javascript expert but did find that in the refresh function line 6237 in tessera.js that 'this' does not point to the manager object but the actual window which doesn't have the 'current' object and as such skips the load function all together.

Hope that helps.
Jozef

**Comment by aalpern** [comment]
Whoops - thanks! Will get that fixed up shortly.

**Comment by aalpern** [comment]
Fixed

**Comment by jve** [comment]
Great thanks for the quick turnaround!
