### ISSUE TITLE
Log scale

### ISSUE THREAD

**Issue by Kornel** [urbanairship/tessera#480]
Hi,
 it would be great if tessera supported log scale on the y-axis of a e.g. standard time series graph.

That's a tiny yet powerful feature to display spikes in response time, lag, choose-your-metric. Currently a huge spike makes the chart unreadable. Setting a predefined max is not enough.

 Any thoughts on this?

Cheers,
 Kornel

**Comment by aalpern** [comment]
Done

**Comment by Kornel** [comment]
works great, thanks
