### ISSUE TITLE
Small numbers interpreted wrongly

### ISSUE THREAD

**Issue by Xaroth** [urbanairship/tessera#485]
When loading 'small' numbers (i.e. my 5 minute load averages), tessera displays these wrongly:

renderer: flot:
![image](https://cloud.githubusercontent.com/assets/180744/9291026/2ed51b3e-43aa-11e5-882e-351c4756c46b.png)

renderer: graphite:
![image](https://cloud.githubusercontent.com/assets/180744/9291029/4bd10b44-43aa-11e5-9bb2-8a797c4ded02.png)

**Comment by aalpern** [comment]
If you're referring the y-axis label, it's not incorrect - it's just a different format that you're getting from Graphite by default. The values are rendered by `d3.format` with [metric prefixes](https://en.wikipedia.org/wiki/Metric_prefix) --  `400m` is the same as `0.40`.

**Comment by Xaroth** [comment]
Fair point, however, in cases like this or others where small datapoints are being tracked it would be useful if it was possible to 'ignore' the default formatter.

**Comment by aalpern** [comment]
We can add the ability to specify the y-axis format string, but you'll still be limited by what you can do with  a [d3 format string](https://github.com/mbostock/d3/wiki/Formatting). Implementing different formats according to value ranges is pushing into a level of complexity that the current editing UI can't really handle, however.
