### ISSUE TITLE
Hide zero's in tooltip

### ISSUE THREAD

**Issue by Kornel** [urbanairship/tessera#499]
When I'm having multiple series in my chart, the tooltip legend should hide zero entries like I can hide them in the legend with the "series/hide zero legend" option.

When dealing with chart's where the source can come and leave (like machines in the cloud) this seems reasonable :)

See e.g.:
<img width="909" alt="screen shot 2015-08-28 at 15 45 56" src="https://cloud.githubusercontent.com/assets/628457/9548111/d7268e14-4d9e-11e5-9411-e97b1cf5ada4.png">

**Comment by aalpern** [comment]
This was done just recently in release 0.8 - see issue #472. Are you running the latest code?

**Comment by Kornel** [comment]
As a matter of fact I'm not, guess you can close this one. Thanks.
