### ISSUE TITLE
Settings don't persist

### ISSUE THREAD

**Issue by thezerobit** [urbanairship/tessera#500]
I find myself setting the time zone and refresh settings quite often. It would be nice if these persisted between sessions.

**Comment by aalpern** [comment]
They are persisted in an anonymous session cookie - that should be relatively durable as long as your cookies aren't being cleared, or you're not visiting another instance of tessera that shares the same `SECRET_KEY` setting.

**Comment by aalpern** [comment]
Ah, setting the `permanent` flag on the session instance may help - http://flask.pocoo.org/docs/0.10/api/#flask.session

**Comment by aalpern** [comment]
I didn't run into this because Chrome breaks session cookie ephemerality: http://stackoverflow.com/questions/10617954/chrome-doesnt-delete-session-cookies

**Comment by aalpern** [comment]
Fixed.
