### ISSUE TITLE
Legend for graphs appears outside of browser

### ISSUE THREAD

**Issue by deejay1** [urbanairship/tessera#514]
When hovering over the graphs, the legend appears "outside" the browser window so it's not visible
![tessera](https://cloud.githubusercontent.com/assets/41211/9730251/9451dc0e-5615-11e5-9b3f-f3766f3a5f33.png)
It should rather be swapped to appear inside the main window.

**Comment by aalpern** [comment]
Fixed. That one turned out to be pretty easy.

**Comment by deejay1** [comment]
Great, thanks!
