### ISSUE TITLE
Add labels for the targets

### ISSUE THREAD

**Issue by i-am-dror** [urbanairship/tessera#531]
would be very nice to be able to add labels to the legend. 

![screen shot 2015-11-03 at 2 02 23 pm](https://cloud.githubusercontent.com/assets/530407/10907533/8decbf92-8233-11e5-8e5b-23d8bb94ac59.png)

**Comment by aalpern** [comment]
What you see there are labels - you can control what's displayed in the label using Graphite's numerous alias functions.
